### PR TITLE
Change link to RFC based on credentials

### PR DESCRIPTION
**Pull request by GaryGSC**

### CODE REVIEW

**Comment by GaryGSC** [comment]
The ServiceNow API gives no indication if we're hitting production or sandbox, and token we use doesn't have that metadata either. So, the solution here is to get a JWT using the same token and then inspect that.

We'll need to subscribe to the Echo service. @joshgubler 

Any thoughts on the language in the warning message? I didn't want the action to fail if the RFC was raised but we couldn't figure out if it was done in production.

**Comment by joshgubler** [comment]
Props for `console.log(🤷)`

**Comment by joshgubler** [comment]
I'll add the subscription to echo and approve.

**Comment by joshgubler** [comment]
Subscribed to echo v1

**Review by joshgubler — APPROVED** [review]

**Pull request merged**
