### PR TITLE
Fallback Username

### LINKED ISSUE #16: Handle Dependabot auto-merges
Dependabot merging automatically means that Dependabot is the one "pushing" and therefore triggering a standard change.

Dependabot doesn't have a user in ServiceNow.

### PR DESCRIPTION
**Pull request by blakemorgan**
Adds `fallback-username` input so PR's don't fail if the user can't be found in ServiceNow. Example: the fallback username is the primary developer of the system. If it is a dependabot PR, it can be automerged and the RFC assigned to that developer.

- Update dependencies
- Add fallback username

Fixes #16

### CODE REVIEW

**Comment by GaryGSC** [comment]
This makes me uncomfortable. I realize this behavior is opt-in, but I picture the following scenario happening:
- Dev 1 wants Dependabot PR auto-merging to work, so they add their own username as the `fallback-username`
- Newly-onboarded Dev 2 crafts a PR or pushes directly to the repo, without ever associating their GitHub username with their account in ServiceNow
- Dev 2's commits get misattributed to Dev 1 without Dev 2 getting any indication that something was wrong - they'd have to click through to the RFC in ServiceNow, and even then, they might not realize anything was up
...
- Dev 1 goes on vacation
- Dev 2 pushes some commits
- Something goes horribly wrong, perhaps entirely unrelated to any changes
- Operations checks ServiceNow and sees that Dev 1 made changes recently; they frantically try to contact Dev 1

**Review by yoshutch — COMMENTED** [review]
I like this solution. The only issue I can see could be if anyone abuses this to sidestep assigning RFCs to the person committing the code.

**Comment by yoshutch** [comment]
Is there a way to check if the github user that's making the commit/merge is the dependabot user? Then maybe update the RFC short description (or description) to indicate that it's an auto-merge of some kind and then assign the RFC to a fallback-user?

**Comment by jvisker** [comment]
@GaryGSC I thought at one point we were looking at using a non-person for dependabot changes. Am I a just making something up?

**Comment by blakemorgan** [comment]
@GaryGSC I agree with those concerns. However, I feel the benefits of auto-merging dependabot requests outweigh the likelihood of those scenarios happening. I'd imagine that we get more problems with not being able to auto-merge than we do with people not having a GitHub name in ServiceNow. So IMO, we should adjust the action to fix the problem currently happening frequently rather than the problem that, while can happen hypothetically, may not actually that big of an issue.

@yoshutch We can do that, but it would require hardcoding the dependabot username into the action (which I'm fine doing). I just thought this would be better than hardcoding a string.

**Comment by jvisker** [comment]
I think we either hardcode dependabot or add another input to specify the user to fall back for, but I do agree with @GaryGSC that I don't think it should fall back for any user.

**Comment by GaryGSC** [comment]
If the goal is to handle Dependabot, then I'd rather do that directly than provide developers with a potential footgun. I vote for the `if (isDependabot) netId = 'some appropriate Net ID'` option.

**Comment by blakemorgan** [comment]
So something like this (replacing lines 43-44)?

```javascript
if (payload.pusher.name === 'dependabot[bot]') return getInput('dependabot-fallback')
```

**Comment by GaryGSC** [comment]
With some additional error handling, yeah. We don't want developers being confused when Dependabot PRs are failing with a message like "could not get dependabot-fallback input".

**Comment by GaryGSC** [comment]
Sorry if I've come across as combative, BTW. That wasn't my intent. I appreciate that you're looking into this pain point!

**Comment by GaryGSC** [comment]
> @GaryGSC I thought at one point we were looking at using a non-person for dependabot changes. Am I a just making something up?

I think that'd be a really clean solution. It'd make it clearer to Operations that the change was an automated action. They might not know what to do with that information, but at least it wouldn't be misleading. I don't know where that work ended up.

Edit: According to [this Slack thread](https://byu-oit.slack.com/archives/C18T2SYTT/p1602779420069800?thread_ts=1601313473.013500&cid=C18T2SYTT), the Dependabot user exists in ServiceNow.

**Comment by jvisker** [comment]
@GaryGSC Seems like we could 'dependbot' as the fallback user already then.

**Comment by GaryGSC** [comment]
@blakemorgan Assuming we can associate Dependabot PRs with that Dependabot user, would you still want the option to associate those with a named developer instead?

**Comment by blakemorgan** [comment]
You're not being combative. 

I've pushed those changes. I just want deploys triggered by Dependabot to succeed. If that's done by having a Dependabot user in SN, I'm fine with that. I just don't want to keep waiting for that to get set up, so I went ahead and made this PR so at least there is something that can be done immediately. I would like to move past this shortcoming because each week, payments-ws gets about 18 PRs for the @aws-sdk and I'd like to not have to take care of them manually.

**Review by GaryGSC — APPROVED** [review]
Even without using the `dependbot` user in ServiceNow, this LGTM now.

**Pull request merged**
